name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:

    runs-on: ubuntu-latest

    env:
      NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
      NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Type check
      run: npm run type-check || true

    - name: Lint
      run: npm run lint || true

    - name: Run tests
      run: npm run test || true

    - name: Setup CI environment
      run: |
        cp .env.ci .env.production
        echo "Using CI-specific environment configuration"
        
    - name: Build
      run: |
        export SKIP_SUPABASE_INIT_ON_BUILD=true
        export NEXT_PUBLIC_DISABLE_SSR_IN_CI=true
        export NEXT_PUBLIC_CI_BUILD=true
        npm run build

  deploy-preview:
    needs: ci
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    environment:
      name: Preview
      url: ${{ steps.deploy-preview.outputs.preview-url }}

    steps:
    - uses: actions/checkout@v3

    - name: Setup CI environment for preview
      run: |
        cp .env.ci .env.production
        echo "Using CI-specific environment configuration for preview deployment"
        
    - name: Deploy to Vercel (Preview)
      id: deploy-preview
      uses: amondnet/vercel-action@v20
      env:
        SKIP_SUPABASE_INIT_ON_BUILD: true
        NEXT_PUBLIC_DISABLE_SSR_IN_CI: true
        NEXT_PUBLIC_CI_BUILD: true
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
        vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
        github-token: ${{ secrets.GITHUB_TOKEN }}

  deploy-production:
    needs: ci
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    environment:
      name: Production
      url: ${{ steps.deploy-production.outputs.preview-url }}

    steps:
    - uses: actions/checkout@v3

    - name: Setup CI environment for production
      run: |
        cp .env.ci .env.production
        echo "Using CI-specific environment configuration for production deployment"
        
    - name: Deploy to Vercel (Production)
      id: deploy-production
      uses: amondnet/vercel-action@v20
      env:
        SKIP_SUPABASE_INIT_ON_BUILD: true
        NEXT_PUBLIC_DISABLE_SSR_IN_CI: true
        NEXT_PUBLIC_CI_BUILD: true
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
        vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
        github-token: ${{ secrets.GITHUB_TOKEN }}
        vercel-args: '--prod'
